### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by lostopkk** [Urbaeexyz/wa-bot#12]
[EROR] TypeError: Cannot read property 'replace' of undefined
    at Tokenizer.parseHtmlEnteties (C:\Users\lostopkk\Desktop\wa-bot-main\node_modules\sastrawijs\tokenizer.js:5:24)
    at Tokenizer.tokenize (C:\Users\lostopkk\Desktop\wa-bot-main\node_modules\sastrawijs\tokenizer.js:11:29)
    at C:\Users\lostopkk\Desktop\wa-bot-main\lib\kataKotor.js:23:27
    at new Promise (<anonymous>)
    at cariKasar (C:\Users\lostopkk\Desktop\wa-bot-main\lib\kataKotor.js:19:40)
    at HandleMsg (C:\Users\lostopkk\Desktop\wa-bot-main\HandleMsg.js:229:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by lostopkk** [comment]
> that's for badwords

how to disable?
