### ISSUE TITLE
Play ngapa ngab?:'v

### ISSUE THREAD

**Issue by yoga875** [Urbaeexyz/wa-bot#48]
(node:5124) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
    at createError (c:\wa-bot-main\node_modules\axios\lib\core\createError.js:16:15)
    at settle (c:\wa-bot-main\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)(node:5124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)

**Comment by Urbaeexyz** [comment]
> (node:5124) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
> at createError (c:\wa-bot-main\node_modules\axios\lib\core\createError.js:16:15)
> at settle (c:\wa-bot-main\node_modules\axios\lib\core\settle.js:17:12)
> at IncomingMessage.handleStreamEnd (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:260:11)
> at IncomingMessage.emit (events.js:387:35)
> at endReadableNT (internal/streams/readable.js:1317:12)
> at processTicksAndRejections (internal/process/task_queues.js:82:21)(node:5124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)

rest apinya lagi error kali

**Comment by Urbaeexyz** [comment]
> (node:5124) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
> at createError (c:\wa-bot-main\node_modules\axios\lib\core\createError.js:16:15)
> at settle (c:\wa-bot-main\node_modules\axios\lib\core\settle.js:17:12)
> at IncomingMessage.handleStreamEnd (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:260:11)
> at IncomingMessage.emit (events.js:387:35)
> at endReadableNT (internal/streams/readable.js:1317:12)
> at processTicksAndRejections (internal/process/task_queues.js:82:21)(node:5124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)

dah di fixed, coba test, kalo masih error, komen lagi

**Comment by Urbaeexyz** [comment]
https://github.com/Urbaeexyz/wa-bot/commit/4c1e5cd41eb230d63ec5a3d0d1bfab4a816e166a
