### ISSUE TITLE
Error When Start 

### ISSUE THREAD

**Issue by irfansaf** [Urbaeexyz/wa-bot#7]
{ Error: ENOENT: no such file or directory, open '/home/irfansaf/wa-bot/node_modules/figlet/fonts/slant.flf'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Function.figlet.loadFontSync (/home/irfansaf/wa-bot/node_modules/figlet/lib/node-figlet.js:48:23)
    at Function.me.textSync (/home/irfansaf/wa-bot/node_modules/figlet/lib/figlet.js:879:43)
    at start (/home/irfansaf/wa-bot/index.js:11:34)
    at create.then (/home/irfansaf/wa-bot/index.js:49:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',

**Comment by Urbaeexyz** [comment]
what kind font u use?

**Comment by Urbaeexyz** [comment]
kentod, org indo so soan inggris:v

**Comment by Urbaeexyz** [comment]
> { Error: ENOENT: no such file or directory, open '/home/irfansaf/wa-bot/node_modules/figlet/fonts/slant.flf'
> at Object.openSync (fs.js:443:3)
> at Object.readFileSync (fs.js:343:35)
> at Function.figlet.loadFontSync (/home/irfansaf/wa-bot/node_modules/figlet/lib/node-figlet.js:48:23)
> at Function.me.textSync (/home/irfansaf/wa-bot/node_modules/figlet/lib/figlet.js:879:43)
> at start (/home/irfansaf/wa-bot/index.js:11:34)
> at create.then (/home/irfansaf/wa-bot/index.js:49:22)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> errno: -2,
> syscall: 'open',
> code: 'ENOENT',

udah tuh, tinggal ganti aja nama fontnya
kalau ga tau, ada update di index.js
cek aja
